application: crowdspeakers
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: jinja2
  version: latest

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: /pics
  static_dir: pics

- url: /.*
  script: CrowdSpeakers.py

builtins:
- remote_api: on